# Generated by Django 6.1 on 2026-08-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarkovItem',
            fields=[
                ('api_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='API 고유 ID')),
                ('category', models.CharField(choices=[('meds', '의료품 / 주사기'), ('backpack', '가방'), ('rig', '리그(체스트리그)'), ('ammo', '탄약')], db_index=True, max_length=20, verbose_name='분류')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='축약 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('icon_link', models.URLField(blank=True, max_length=500, verbose_name='아이콘 URL')),
                ('image_link', models.URLField(blank=True, max_length=500, verbose_name='큰 이미지 URL')),
                ('wiki_link', models.URLField(blank=True, max_length=500, verbose_name='위키 URL')),
                ('width', models.PositiveSmallIntegerField(default=1, verbose_name='가로 칸')),
                ('height', models.PositiveSmallIntegerField(default=1, verbose_name='세로 칸')),
                ('base_price', models.IntegerField(default=0, verbose_name='기본가')),
                ('avg_24h_price', models.IntegerField(blank=True, null=True, verbose_name='24시간 평균가')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='상세 스펙')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='동기화 시각')),
            ],
            options={
                'verbose_name': '타르코프 아이템',
                'verbose_name_plural': '타르코프 아이템',
                'ordering': ['name'],
            },
        ),
    ]
