# Generated by Django 6.1.1 on 2026-09-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('api_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='API ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='축약명')),
                ('icon_link', models.URLField(blank=True, max_length=500, verbose_name='아이콘')),
                ('wiki_link', models.URLField(blank=True, max_length=500, verbose_name='위키')),
                ('mod_type', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='부품 종류')),
                ('ergonomics', models.FloatField(blank=True, null=True, verbose_name='조준편의 변화')),
                ('recoil_modifier', models.FloatField(blank=True, null=True, verbose_name='반동 변화율')),
                ('accuracy_modifier', models.FloatField(blank=True, null=True, verbose_name='정확도 변화율')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('slots_raw', models.JSONField(blank=True, default=list, verbose_name='하위 슬롯')),
            ],
            options={
                'verbose_name': '부품',
                'verbose_name_plural': '부품',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('api_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='API ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='축약명')),
                ('icon_link', models.URLField(blank=True, max_length=500, verbose_name='아이콘')),
                ('wiki_link', models.URLField(blank=True, max_length=500, verbose_name='위키')),
                ('caliber', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='구경')),
                ('ergonomics', models.FloatField(blank=True, null=True, verbose_name='조준편의')),
                ('recoil_vertical', models.IntegerField(blank=True, null=True, verbose_name='세로 반동')),
                ('recoil_horizontal', models.IntegerField(blank=True, null=True, verbose_name='가로 반동')),
                ('fire_rate', models.IntegerField(blank=True, null=True, verbose_name='연사속도(RPM)')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('slots_raw', models.JSONField(blank=True, default=list, verbose_name='슬롯 원본')),
            ],
            options={
                'verbose_name': '총기',
                'verbose_name_plural': '총기',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('api_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='API ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('base_name', models.CharField(blank=True, max_length=255, verbose_name='기반 총기명')),
                ('icon_link', models.URLField(blank=True, max_length=500, verbose_name='아이콘')),
                ('wiki_link', models.URLField(blank=True, max_length=500, verbose_name='위키')),
                ('ergonomics', models.FloatField(blank=True, null=True, verbose_name='조준편의')),
                ('recoil_vertical', models.IntegerField(blank=True, null=True, verbose_name='세로 반동')),
                ('recoil_horizontal', models.IntegerField(blank=True, null=True, verbose_name='가로 반동')),
                ('moa', models.FloatField(blank=True, null=True, verbose_name='정확도(MOA)')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 프리셋')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('base_weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='mods.weapon', verbose_name='기반 총기')),
            ],
            options={
                'verbose_name': '프리셋',
                'verbose_name_plural': '프리셋',
                'ordering': ['base_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SlotOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(db_index=True, max_length=120, verbose_name='슬롯 이름')),
                ('slot_order', models.PositiveSmallIntegerField(default=0, verbose_name='슬롯 순서')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fits_slots', to='mods.mod')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_options', to='mods.weapon')),
            ],
            options={
                'verbose_name': '슬롯 장착 옵션',
                'verbose_name_plural': '슬롯 장착 옵션',
                'indexes': [models.Index(fields=['weapon', 'slot_order'], name='mods_slotop_weapon__3f0c59_idx')],
                'unique_together': {('weapon', 'slot_name', 'mod')},
            },
        ),
    ]
